export enum ACTIONS { 
    GET_DISCOUNTSCHEMES_REQUEST = "GET_DISCOUNTSCHEMES_REQUEST",
    GET_DISCOUNTSCHEMES_RECEIVED = "GET_DISCOUNTSCHEMES_RECEIVED",

    GET_DISCOUNTSCHEME_REQUEST = "GET_DISCOUNTSCHEME_REQUEST",
    GET_DISCOUNTSCHEME_RECEIVED = "GET_DISCOUNTSCHEME_RECEIVED",

    GET_BIDSOFCUSTOMER_INCART_REQUEST = "GET_BIDSOFCUSTOMER_INCART_REQUEST",
    GET_BIDSOFCUSTOMER_INCART_RECEIVED = "GET_BIDSOFCUSTOMER_INCART_RECEIVED",

    ADD_BID_TO_CART_REQUEST = "ADD_BID_TO_CART_REQUEST",
    ADD_BID_TO_CART_RECEIVED = "ADD_BID_TO_CART_RECEIVED",

    UPDATE_BID_IN_CART_REQUEST = "UPDATE_BID_IN_CART_REQUEST",
    UPDATE_BID_IN_CART_RECEIVED = "UPDATE_BID_IN_CART_RECEIVED",

    ERROR = "ERROR",
    CLEAR_ERROR = "CLEAR_ERROR"
}






