export enum ACTIONS { 
    GET_DISCOUNTSCHEMES_REQUEST = "GET_DISCOUNTSCHEMES_REQUEST",
    GET_DISCOUNTSCHEMES_RECEIVED = "GET_DISCOUNTSCHEMES_RECEIVED",

    GET_DISCOUNTSCHEME_REQUEST = "GET_DISCOUNTSCHEME_REQUEST",
    GET_DISCOUNTSCHEME_RECEIVED = "GET_DISCOUNTSCHEME_RECEIVED",

    GET_DISCOUNTSCHEME_OF_PRODUCER_REQUEST = "GET_DISCOUNTSCHEME_OF_PRODUCER_REQUEST",
    GET_DISCOUNTSCHEME_OF_PRODUCER_RECEIVED = "GET_DISCOUNTSCHEME_OF_PRODUCER_RECEIVED",

    GET_BIDSOFCUSTOMER_INCART_REQUEST = "GET_BIDSOFCUSTOMER_INCART_REQUEST",
    GET_BIDSOFCUSTOMER_INCART_RECEIVED = "GET_BIDSOFCUSTOMER_INCART_RECEIVED",

    ADD_BID_TO_CART_REQUEST = "ADD_BID_TO_CART_REQUEST",
    ADD_BID_TO_CART_RECEIVED = "ADD_BID_TO_CART_RECEIVED",

    UPDATE_BID_IN_CART_REQUEST = "UPDATE_BID_IN_CART_REQUEST",
    UPDATE_BID_IN_CART_RECEIVED = "UPDATE_BID_IN_CART_RECEIVED",

    DELETE_BID_IN_CART_REQUEST = "DELETE_BID_IN_CART_REQUEST",
    DELETE_BID_IN_CART_RECEIVED = "DELETE_BID_IN_CART_RECEIVED",

    ERROR = "ERROR",
    CLEAR_ERROR = "CLEAR_ERROR",

    ORDER_BIDS_IN_CART_REQUEST = "ORDER_BIDS_IN_CART_REQUEST",
    ORDER_BIDS_IN_CART_RECEIVED = "ORDER_BIDS_IN_CART_RECEIVED",

    GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_RECEIVED = "GET_PRODUCTS_RECEIVED",

    GET_PENDING_OR_SUCCESSFUL_BIDS_REQUEST = "GET_PENDING_OR_SUCCESSFUL_BIDS_REQUEST",
    GET_PENDING_OR_SUCCESSFUL_BIDS_RECEIVED = "GET_PENDING_OR_SUCCESSFUL_BIDS_RECEIVED",

    HTTP_UPDATE_SUCCESS = "HTTP_UPDATE_SUCCESS",
    HTTP_READ_SUCCESS = "HTTP_READ_SUCCESS",
    HTTP_CREATE_SUCCESS = "HTTP_CREATE_SUCCESS",
    HTTP_DELETE_SUCCESS = "HTTP_DELETE_SUCCESS",

    HTTP_UPDATE_ORDER_SUCCESS = "HTTP_UPDATE_ORDER_SUCCESS"
}






